### ISSUE TITLE
Failed to add QoS entry

### ISSUE THREAD

**Issue by bzhpwr** [RealOpInsightLabs/realopinsight-ultimate#1]
Hi, 

After some time, RealOpInsight stop to insert Qos entry but realopinsight-reportd is steel running.

realopinsight-reportd.log:
2016-11-28T13:47:11 [notice] Failed to add QoS entry, please check the log file

realopinsight.log:
2016-11-28T13:47:11 [error] int DbSession::addQosData(const QosDataT&): Wt::Dbo::ptr: null dereference
2016-11-28T13:49:51 [error] int DbSession::listQosData(QosDataListMapT&, const string&, long int, long int): Wt::Dbo::ptr: null dereference

Version: 2016r1
Codename: Universe
Release ID: 2016r1/2016
OS: Ubuntu 14.04.1

**Comment by rchakode** [comment]
Hi,
Did you try to restart the reportd service?
This error may be due to a conflicting access to the database by the different application process.

**Comment by bzhpwr** [comment]
Hi, 

I have restart reportd this morning.
Same error after few minutes:

/opt/realopinsight/log/realopinsight-reportd.log:
2016-11-29T11:31:56 [notice] Failed to add QoS entry, please check the log file

/opt/realopinsight/log/realopinsight.log
2016-11-29T11:31:56 [error] int DbSession::addQosData(const QosDataT&): Wt::Dbo::ptr: null dereference

**Comment by rchakode** [comment]
is it the first time that you experience this problem ?
If yes, can tell us what changed on your system please ?

**Comment by bzhpwr** [comment]
I update Rois a month ago but I can't tell you if it's working before because I didn't use it since a long time ago.

**Comment by bzhpwr** [comment]
I'm creating a new VM with the last Rois Ultimate Appliance.
I'll tell you if this resolve this bug.

**Comment by rchakode** [comment]
Hi,
thank you for the feedback, let us know your finding to help investigate the issue.
try to have at least 2 vCPU for the virtual machine.

**Comment by bzhpwr** [comment]
Hi, 
I can't load RealOpInsight Ultimate Appliance in VMWare Vcenter so I re-install it by binaries
OS: Ubuntu 14.04.5 LTS 
vCPU: 4
Ram: 2Go

I load all my maps, views are working.
But now I have no qos entry anymore.
realopinsight-server & realopinsight-reportd are running ( I restarted them )
log/realopinsight-reportd.log is empty.
table qosdata in realopinsight.db is empty too.

An idea ?

**Comment by rchakode** [comment]
Hi @bzhpwr,
Thank you for this new info, we're working on this and will let you kown.
R.

**Comment by rchakode** [comment]
Hi,
can you tell us how many business services you manage please?

**Comment by rchakode** [comment]
Fixed in version 2018r1, required advanced database backend as PostgreSQL currently supported.
